FROM node:alpine     
USER node
EXPOSE 3000     
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
     
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./     
CMD ["npm", "start"]
